[build]
  publish = "."

# Enable CORS for form submissions from your GitHub Pages site
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://trondheimatletklubb.github.io"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Redirect after successful form submission
[[redirects]]
  from = "/contact-success"
  to = "/success.html"
  status = 200
